// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh_ao0Aq_UiLEIu5LdJhpd5fyot9ojoGQ',
    appId: '1:252526625716:web:abf878ada452f49141a8e1',
    messagingSenderId: '252526625716',
    projectId: 'grocerystore-6a49c',
    authDomain: 'grocerystore-6a49c.firebaseapp.com',
    storageBucket: 'grocerystore-6a49c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5d6xvmgxf7RjppHyg8SRC_4zla9kEcwo',
    appId: '1:252526625716:android:173588be24f3f3c041a8e1',
    messagingSenderId: '252526625716',
    projectId: 'grocerystore-6a49c',
    storageBucket: 'grocerystore-6a49c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAibdc41TwXb-1OiiyW8YK17sk25edPbC8',
    appId: '1:252526625716:ios:bd2b55b34506c00341a8e1',
    messagingSenderId: '252526625716',
    projectId: 'grocerystore-6a49c',
    storageBucket: 'grocerystore-6a49c.appspot.com',
    iosBundleId: 'com.example.groceryStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAibdc41TwXb-1OiiyW8YK17sk25edPbC8',
    appId: '1:252526625716:ios:6cde809ebfa2604d41a8e1',
    messagingSenderId: '252526625716',
    projectId: 'grocerystore-6a49c',
    storageBucket: 'grocerystore-6a49c.appspot.com',
    iosBundleId: 'com.example.groceryStoreApp.RunnerTests',
  );
}
